---
title: The story of this drawing
author: Allison Horst
date: '2020-03-15'
slug: []
categories:
  - art
  - R
  - RStudio
tags:
  - art
  - R
  - RStudio
subtitle: ''
summary: ''
authors: []
lastmod: ''
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Walking through the door

I am always happy to see this illustration used to represent of the welcoming and encouraging #rstats community on twitter. When I drew it, my view was much smaller: I wanted to visualize how Dr. Julie Lowndes (Twitter: [\@juliesquid](https://twitter.com/juliesquid), website: https://jules32.github.io/) had gently encouraged me to join twitter for the R community, and the amazement I felt upon opening the door. I was late to the party - finally dipping my toes into the #rstats twitter water in 2018. Two years later, it's now my go-to place for:

- Staying up-to-date on what's new in R
- Meeting and communicating with new friends and collaborators 
- Learning new ideas and approaches for teaching stats and data science
- Sharing my course materials and artwork
- Listening to, and learning from, a diverse range of voices in R/data science/environmental science 

The rumors are true, people. It's **the** place to be if you're learning, using, or teaching R. 

### R is better together

I've been teaching stats & data analysis in R at the [Bren School of Environmental Science and Management](http://bren.ucsb.edu/) since 2012. But *using and teaching R* is very different from being a *happy R user and teacher*. 

Frankly, I was a lonely R user flailing around without a home base, and I didn't even realize how much of a bummer that was. 

In 2017, Julie serendipitously moved in to a cabin just one short down the road from me. Do you know what happens when you finally get to hang out with someone who loves using and teaching R as much as you do? **You hang out all the time and never shut up about it.** 

It's obnoxious. 

We talk about using R on every hike. 

We talk about teaching R over bonfires. 

We talk about building inclusive R communities while romping with our dogs, Teddy and Khora, in the riverbed. 

We talk about R frustrations while eating pizza.

We talk about R at SB R-Ladies (https://twitter.com/RLadiesSB), UCSB TidyTuesdays, and [Eco-Data-Science](https://eco-data-science.github.io/).

It's so obnoxious. 



### Joining twitter for R stats

### Using twitter for R





